- lua/dressing/select/telescope.lua
Hello, thanks for this great plugin! I've been running into some nil access errors when not selecting anything from the telescope menu (for example, [when searching for an entry that doesn't exist so that it clears the results, and then press enter](https://asciinema.org/a/kCM12JgpsuK3ysYAaqNaTvJF2)). Figured that doing a simple check would make sense here
> fix(select/telescope): check for nil selection

- lua/dressing/select/telescope.lua
This PR adds the ability for a user to specify the options they would like to add to the telescope picker. Currently, a user can only choose a theme as a string but cannot determine things like the width, height, border characters etc. This PR adds the ability for a user to pass the theme object *or a string* to dressing to have that be used by telescope.
e.g.
```lua
use {'dressing.nvim', config = function()
config = function()
require('dressing').setup {
select = {
winblend = 2,
telescope = {
theme = require('telescope.themes').get_cursor { -- or 'cursor'
border_chars = {chars_i_like},
layout_config = {
height = function(self, _, max_lines)
return random_height_i_computed
end,
},
},
},
},
}
end
```
This is similar to how https://github.com/nvim-telescope/telescope-ui-select.nvim works, …
> fix(telescope): allow passing theme options to select

- lua/dressing/select/telescope.lua
Support passing extra telescope configurations as well as custom theme
function + backward compatibility for current state. So hopefully no
breaking changes.
> feat(select): override telescope config

- autoload/dressing.vim
`fzf.vim` provides both `fzf#run` and `fzf#wrap`. The latter function is used to force `fzf#run` to respect user options defined in e.g. `g:fzf_layout`. I believe it is better to use this so that dressings fzf behaviour respects user options.
See `:help fzf#wrap` for more details.
> Use fzf#wrap to respect user option

- README.md
- lua/dressing/config.lua
- lua/dressing/select/init.lua
_2 sentence summary of change_
`vim.ui.select` prompts may have a trailing semicolon which some users may want to remove from floating window displays. This allows them to remove it :D
_What is the problem you are trying to solve?_
_If related to an issue, please link it here. You may omit some background
details if it is in the issue._
There may be an unnecessary trailing colon from `vim.ui.select` prompts when using floating displays.
_Describe how the changes add the functionality or fix the issue under "Context"_
User can specify whether to automatically trim this trailing colon from select prompts.
_list the steps you took to test this functionality. Steps should be
reproducible by others._
Adjusting config value `trim_prompt` with different backends in tests/manual/select.lua …
> feat: trim trailing colon from prompt

- lua/dressing/select/init.lua
Looks like a copy-paste typo. Introduced in 31f12fff6e71a14ddce30bfc7ec9b29a2137ccde.
> fix(select): use original vim.ui.select if enabled is false

- lua/dressing/config.lua
- lua/dressing/input.lua
- tests/input_spec.lua
Add a new option, `start_in_insert`, that defaults to true and controls whether the input will start in insert or normal mode.
I'd like to conditionally enable normal mode when certain criteria are met, e.g. when using `vim.ui.input` with LSP rename.
This PR introduces an option that controls whether insert mode will be activated or not, and it can be used along with `get_config` for conditional behavior. For instance:
```lua
require('dressing').setup({
input = {
...
get_config = function(opts)
return {
start_in_insert = #(opts.default or '') == 0,
}
end,
}
})
```
Test case 1
- Set `start_in_insert` to `true` in `setup()` (or leave it unset since the default value is true already).
- Run `vim.ui.input({default = "some text"}, function() end)`.
- An input window should open in insert mode. …
> Add start_in_insert option

- lua/dressing/select/fzf_lua.lua
Replace `fzf_wrap` with `fzf_exec` API as discussed in #64
> chore(fzf-lua): use newer 'fzf_exec' API (#64)

- lua/dressing/select/fzf_lua.lua
Pass the `prompt` value given to `vim.ui.select` to [fzf-lua](https://github.com/ibhagwan/fzf-lua)
Currently the select ui never shows any prompt for fzf-lua
See this example which should show the prompt "Code actions"
This is what I would expect (and how it looks with my changes):
Check for a given prompt value in the `opts` parameter, otherwise fall back to "Select one of" (as `vim.ui.select` does by default). Instead of using a colon fzf usually uses the `>` as a delimiter for the prompt which is why I did so as well.
> fix(fzf-lua): pass prompt option to fzf

- README.md
- doc/dressing.txt
- lua/dressing/map_util.lua
Allow additional opts to be passed to vim.keymap.set().
I want to pass `{ nowait = true }`.
Allow additional opts to be passed to vim.keymap.set().
Define an nmap that begins with `<Esc>` as follows, and pass `{ nowait = true }` to see if the delay exists.
`nnoremap <Esc><Esc> <Cmd>nohl<CR>`
> feat: allow to pass extra opts to vim.keymap.set()

- lua/dressing/select/builtin.lua
> feat: bind keymap, add number prefix

- README.md
Corrects the example in the `README` about how to use `winhiglight` for customizing highlights.
Follow-up of #101.
> docs: fix winhighlight example

- README.md
- lua/dressing/config.lua
- lua/dressing/input.lua
Give `input` the same `trim_prompt` setting `select` already has.
_What is the problem you are trying to solve?_  
It's really only a minor aesthetic improvement. Also makes `input` and `select` more consistent, as they both now have a `trim_prompt` setting.
_Describe how the changes add the functionality or fix the issue under "Context"_
The gist of it: if `input.trim_only` then `title = title:gsub(":$", "")`.
_list the steps you took to test this functionality. Steps should be
reproducible by others._
confirm that it works correctly: 
```lua
require("dressing").setup { input = { trim_prompt = true } }
vim.ui.input({ prompt = "Input: " }, function () end)
```
```lua
require("dressing").setup { input = { trim_prompt = false } }
vim.ui.input({ prompt = "Input: " }, function () end)
```
> feat: add `trim_prompt` setting for `vim.ui.input`

- lua/dressing/select/builtin.lua
- lua/dressing/select/nui.lua
Width calculation logic in nui and builtin selects ignores prompt size. This makes it very easy to lose crucial information required to make a decision.
For example, here's what I see when running `LspStart` with the `vtsls` language server with master of `stevearc/dressing.nvim`:
And here's what I see with this PR:
Initialize `max_width` (builtin) or `line_width` (nui) to the prompt length if it exists. Otherwise fallback to previous value of 1.
Used the manual select test with the following configuration:
```
-- Run this test with :source %
local function run_test(backend)
local config = require("dressing.config")
local prev_backend = config.select.backend
config.select.backend = backend
vim.ui.select({
"first",
"second",
"third",
}, {
prompt = "Make a very informed selection after …
```
> fix: take into account prompt size in nui and builtin selects

- lua/dressing/select/fzf.lua
add space after prompt for fzf backend to look good
Using fzf as backend, without this extra space, the prompt gets mixed with the ones we are typing making it unable to read like in the below screenshot
Even after disabling trim_prompts it looks like this which is little bit unclear to read
It adds an extra space to the prompt making it look cleaner and seperates the input from prompt making it readable like in the screenshot below
Without trim prompts enabled
With trim prompts enabled
```lua
bootstrap_paq({
{
"junegunn/fzf",
build = ":call fzf#install()",
},
"junegunn/fzf.vim",
"nomnivore/ollama.nvim",
"stevearc/dressing.nvim",
})
require("ollama").setup({
model = "codellama",
url = "http://127.0.0.1:11434",
-- serve = {
--	on_start = false,
--	command = "ollama",
--	args = { "serve" }, …
```
> fix: add space after prompt to look nicer

- lua/dressing/select/init.lua
Handle extra prompt scenario where the prompt has trailing spaces leading to unwanted behaviour.
The way trim_prompt works is that if the last character is ":" it trims it. But the issue is there are plugins like nvim-dap which send prompts like this "Configurations: " with an extra trailing space leading to the addition of extra space by my last pr for fzf backend https://github.com/stevearc/dressing.nvim/pull/136 to add an unwanted extra space. This pr fixes that behaviour.
Behaviour withou this pr
Behaviour with this pr
It changes the prompts functionality by removing trailing spaces from prompts.
```lua
bootstrap_paq({
{
"junegunn/fzf",
build = ":call fzf#install()",
},
"junegunn/fzf.vim",
"stevearc/dressing.nvim",
"mfussenegger/nvim-dap",
{
"microsoft/vscode-js-debug",
build = …
```
> fix: handle extra scenario where the prompt is sent with trailing spaces

- lua/dressing/select/fzf_lua.lua
fzf_lua shows its prompt and user input in the same line and dressing.nvim tries to make prompts like the title of a window, so it causes the prompt and input to be crowded together.
I suggest adding a separator after the prompt.
> feat(fzf-lua): add an input indicator after prompt

- lua/dressing/util.lua
before this change, with vim.ui.input, if the user callback triggers a vim error, dressing would get stuck and all following vim.ui.input invocations would hang/not be processed.
It is possible to reproduce the issue by triggering this vim command:
```
:lua vim.ui.input({prompt=hi}, function(input) vim.api.nvim_win_close(39483904, {}) end)
```
so we try to close a non-existing vim window. That will fail. But after this, trigger the same command again, and the dressing input prompt will not appear. Because the callback throwing "broke" the dressing logic.
Instead of first invoking the user callback and then scheduling the consumption, invert the order to make sure the user callback failing cannot break the dressing logic.
I considered using pcall to invoke the user callback, but if the …
> fix stuck input control if callback fails

- README.md
- doc/dressing.txt
- lua/dressing/config.lua
- lua/dressing/input.lua
- tests/input_spec.lua
Implement `start_mode`. It's like `start_in_insert`, but more flexible.
Implement #174 
I added `start_mode`. I kept `start_in_insert` for backwards compatibility.
I tried each value of `start_mode` with a default value and without. I also added automated tests of the backwards compatibility of `start_in_insert`.
> Add support for start_mode

- lua/dressing/config.lua
#175 does not check for possible nil value of `opts` on `add_shim` (that may come from `:h dressing_get_config()`). Add `nil` check
#175 added `apply_shim` to maintain backwards compatibility, but it doesn't check if `opts` is `nil` before trying to access it. It may be `nil` since `:h dressing_get_config()` allows for a `nil` return value.
A `nil` check is added
My config was broken after #175 since I have the following on my oil setup.
```lua
{
-- ...
input = {
get_config = function(opts)
if opts.prompt == "cmd: " then
return {
-- some custom options
}
end
end,
},
-- ...
}
```
The function returns `nil` to fallback to the default config whe prompt is not `cmd: `. With this config, calling `vim.ui.input({}, function() end)` resulted in an error before this PR and works as expected after …
> fix(apply_shim): add nil check for opts

- README.md
- lua/dressing/config.lua
Disable highlighting of numbers in the `builtin` DressingSelect. (The numbers that are displayed when `show_numbers = true`).
before:
after:
_What is the problem you are trying to solve?_
Only a minor aesthetic one. The highlight of matching parentheses is not useful in the selection window.
> fix(select-builtin): disable highlighting of `[n]` due to MatchParen

- lua/dressing/config.lua
add padding to left border
_If related to an issue, please link it here. You may omit some background
details if it is in the issue._
see #184
_Describe how the changes add the functionality or fix the issue under "Context"_
uses `statuscolumn = " "` to add padding that does not interfere with the cursor.
> fix(input): add padding to left border (fixes #184)

- README.md
- lua/dressing/config.lua
- lua/dressing/select/snacks_picker.lua
Adds the
[snacks picker](https://github.com/folke/snacks.nvim/blob/main/docs/picker.md) backend option.
Like telescope and fzf-lua, it already provides it's own override for `vim.ui.select`, BUT since plugins like avante rely on using dressing.nvim for picking files and such, having a backend that can fuzzy find is more convenient than the builtin.
To setup:
```lua
require("dressing").setup({ select = { enabled = true, backend = "snacks_picker" }})
```
Or using lazy.nvim:
```lua
{
"stevearc/dressing.nvim",
opts = {
select = { enabled = true, backend = "snacks_picker" },
},
}
```
And then run something like:
`:lua vim.ui.select({ "Yes", "No" }, { prompt = "Hello, World!" }, function() end)`
> feat(select): add snacks_picker backend
